### ISSUE TITLE
GCC11 compilation error with IDA Pro 8.1 / SDK8.1

### ISSUE THREAD

**Issue by fxb-cocacoding** [REhints/HexRaysCodeXplorer#109]
Hey,

the current version is not compiling with GCC 11. The following patch can mitigate the issue:
```
diff --git a/src/HexRaysCodeXplorer/TypeReconstructor.cpp b/src/HexRaysCodeXplorer/TypeReconstructor.cpp
index 4cc71f8..f84afc3 100644
--- a/src/HexRaysCodeXplorer/TypeReconstructor.cpp
+++ b/src/HexRaysCodeXplorer/TypeReconstructor.cpp
@@ -28,6 +28,7 @@
 
 #include "Debug.h"
 #include "Utility.h"
+#include <memory>
 
 #if !defined (__LINUX__) && !defined (__MAC__)
 #include <tchar.h>
@@ -742,4 +743,4 @@ bool idaapi reconstruct_type(const reconstruct_type_params_t & params)
        }
 
        return reconstruct_type(cfunc, params.var_name, params.type_name);
-}
\ No newline at end of file
+}
```
The file `TypeReconstructor.cpp` is missing the import `#include <memory>`.

**Comment by nicolaipre** [comment]
Can confirm this also works on IDA Pro 8.3 / SDK 8.3

**Comment by rrbranco** [comment]
We've forward ported everything to IDA 9.2.  Thanks for the report.
